## For information on how to use thie file, see the documentation at the repo home:
## github.com/sahassar/boltredirector

# Redirects - The Main Redirects for this Installation
redirects:
    # Redirects om de topnav goed te laten werken. Linkt door naar eerste child via deze redirect. EP-125
    # parent : first child
    '/page/share-your-data': '/share-your-data/process'
    '/share-your-data': '/share-your-data/process'
    '/page/about-us': '/about-us/mission'
    '/about-us': '/about-us/mission'
    '/page/network-association': ' /network-association/sign-up'
    '/network-association': '/network-association/sign-up'



#    page:
#        from: '{slug:segment}.html'
#        to: '/page/{slug}'

# Variables
#
# A simple array to make variable replacements in destination paths using the
# {@<variable>} syntax.

variables:

# JIT (Just In Time) Replacements
#
# These replacements are made just before the actual redirect, so they
# must match any parts in `to` patterns from the above array.
#
# For conciseness, try to match an entire destination, as other URIs
# could be inadvertantly affected. If other URIs won't contain the
# string, then you can keep it as short as needed.
#
# Also, regular expressions are allowed here. Capture with \\n.
jits:
#    test:
#        replace: 'page/test2'
#        with: 'page/test'
