# debug mode will make this process a lot slower
debug_mode: false
# the path for downloads images in hookafterload
image_path: 'zoho_images'
# set image_downloads to true for the hookafterload images
image_downloads: true

remotes:
    zoho_json_remote:
        enabled: true
        source:
            url: https://crm.zoho.com/crm/private/json/Contacts/getRecords
            getparams:
                authtoken: '{{override in local config}}'
                scope: crmapi
            loopparams:
                counter: fromIndex
                stepper: toIndex
                start: 1       # start at this (should be 1)
                size: 100      # number of records to fetch per iteration
            # generate a token by going to
            # https://accounts.zoho.com/apiauthtoken/create?SCOPE=ZohoCRM/crmapi
            # file: examples/Contacts-Timothy.json
            type: json
        target:
            contenttype: persons
            defaults:
                new: 'published'       # may also be any valid status
                updated: 'published'   # may also be any valid status
                removed: 'held' # may also be any valid status
            hookafterload:
                image:
                    callback: downloadZohoPhotoFromURL
                    source_url: 'https://crm.zoho.com/crm/private/json/Contacts/downloadPhoto?authtoken={{override in local config}}&scope=crmapi&id=CONTACTID'
                    source_field: CONTACTID
                    target_field: image
            mapping: # mappings in XPATH
                root: 'response.result.Contacts.row'
                fields:
                    # bolt_col: "ZOHO Field name"           # example: "Example value"
                    uid: "CONTACTID"                        # example: "1482250000000152005"
                    datecreated: "Created Time"             # example: "2015-06-04 16:37:25"
                    datechanged: "Modified Time"            # example: "2015-06-09 14:44:58"

                    first_name: "First Name"                # example: "Timothy"
                    last_name: "Last Name"                  # example: "Test"

                    email: "Public email"                   # example: "test@browsercheck.nl"
                    phone: "Public phone"                          # example: "0703457628"

                    twitter: "Twitter"                      # example: "twokings"
                    linkedin: "LinkedIn profile"            # example: "https://linkedin.com/in/twokings"
                    skype: "Skype ID"                       # example: "example"

                    introduction: "Description"             # example: "Test record"

                    company: "Account Name"                 # example: "Test"
                    job_title: "Title"                      # example: "Tester"

                    network_participation: "Participation level"
                                                            # example: "Governing Board;Association Members Council"
                    community: "Member of community"        # example: "Data partner;EuropeanaTech (R&D)"
                    community_role: "Community role"        # example: "Test"
                    europeana_tech: "Member of EuropeanaTech"

                    sector: "Sector"
                    country: "Country"
                    boardposition: "Europeana Foundation Board position"

                    # fields that can safely be ignored
                    europeana_id: "ID"                      # default: "EL30MC"
                    # author_uid: "SMOWNERID"                 # example: "1482250000000131003"
                    # author_name: "Contact Owner"            # example: "Bob den Otter"
                    # modified_uid: "MODIFIEDBY"              # example: "1482250000000131003"
                    # modified_name: "Modified By"            # example: "Bob den Otter"
                    # latime: "Last Activity Time"            # example: "2015-06-09 14:44:58"
                    account_uid: "ACCOUNTID"                # example: "1482250000000152017"
                    # statutes_read: "I have read and agree to the statutes"
                                                            # example: "true"
                    # statutes_agree: "I have read and agree to the statutes"
                                                            # example: "true"
                    # public_phone: "Phone"                   # example: "1234567890"
                    # public_email: "Email"            # example: "test@browsercheck.nl"
                    # secondary_email: "Secondary Email"      # example: "twest2@browsercheck.nl"
                    # other_number: "Mobile"                  # example: "+316123456789"
                    # community: "Interested in..."           # example: "Data partner;EuropeanaTech (R&D)
                    public_photo: "Show photo on europeana site"
                                                            # example: "true"
    zoho_json_remote_orgs:
        enabled: true
        source:
            url: https://crm.zoho.com/crm/private/json/Accounts/searchRecords
            # https://crm.zoho.com/crm/private/json/Accounts/searchRecords?authtoken=e95153d23c8b0d4a5eb5c885531f2d6b&scope=crmapi&criteria=%28%28Organisation+role%3AAccredited+Aggregator%29AND%28Aggregator%3AActive%29%29&fromIndex=1&toIndex=100
            getparams:
                authtoken: '{{override in local config}}'
                scope: crmapi
                criteria: '(Organisation Role:Accredited Aggregator)'
                # criteria: '(Organisation Role:Data Provider)'
                # 1. Organisation role: *Accredited Aggregator*
                # 2. Aggregator: *Active*
            loopparams:
                counter: fromIndex
                stepper: toIndex
                start: 1       # start at this (should be 1)
                size: 100      # number of records to fetch per iteration
            # generate a token by going to
            # https://accounts.zoho.com/apiauthtoken/create?SCOPE=ZohoCRM/crmapi
            # file: examples/Contacts-Timothy.json
            type: json
        target:
            contenttype: organisations
            defaults:
                new: 'published'       # may also be any valid status
                updated: 'published'   # may also be any valid status
                removed: 'held' # may also be any valid status
            hookafterload:
                image:
                    callback: downloadZohoPhotoFromURL
                    source_url: 'https://crm.zoho.com/crm/private/json/Accounts/downloadPhoto?authtoken={{override in local config}}&scope=crmapi&id=ACCOUNTID'
                    source_field: ACCOUNTID
                    target_field: image
                relations:
                    callback: loadZohoRelatedRecords
                    source_url: https://crm.zoho.com/crm/private/json/Accounts/getRelatedRecords?authtoken={{override in local config}}&scope=crmapi&parentModule=Contacts&id=ACCOUNTID
                    source_field: ACCOUNTID
                    target_field: null
            mapping: # mappings in XPATH
                root: 'response.result.Accounts.row'
                fields:
                    # bolt_col: "ZOHO Field name"           # example: "Example value"
                    uid: "ACCOUNTID"                        # example: "1482250000000152005"
                    europeana_id: "ID"                      # default: "EL30MC"
                    org_uid: "ACCOUNTID"                # example: "1482250000000152017"
                    datecreated: "Created Time"             # example: "2015-06-04 16:37:25"
                    datechanged: "Modified Time"            # example: "2015-06-09 14:44:58"
                    # last_activity: "Last Activity Time"     # example: "2018-03-12 14:44:00"
                    # modified_date: "MODIFIEDBY"             # example: "1482250000004056005"
                    # modified_by: "Modified By"              # example: "DPS Team"
                    # smuid: "SMOWNERID"                      # example: "1482250000004056005"
                    # account_owner: "Account Owner"          # example: "DPS Team"

                    name: "Account Name"                    # example: "Slovak National Museum"
                    name_lang: "Lang Organisation Name"     # example: "EN(English)"
                    name_alt1: "Alternative 1"              # example: "Slovenské Národné Múzeum"
                    name_alt1_lang: "Lang Alternative 1"    # example: "SK(Slovak)"
                    name_alt2: "Alternative 2"              # example: "Slovenské Národné Múzeum"
                    name_alt2_lang: "Lang Alternative 2"    # example: "SK(Slovak)"
                    acronym: "Acronym"                      # example: "Slovak National Museum"
                    acronym_lang: "Lang Acronym"            # example: "SK(Slovak)"

                    org_country: "Organisation Country"     # example: "Slovakia, SK"
                    org_role: "Organisation Role"           # example: "Example value"

                    website: "Website"                      # example: "http://www.snm.sk"
                    logo_url: "Logo (link to WikimediaCommons)"
                                                            # example: "http://example.com/logo.gif"

                    domain: "Domain"                        # example: "Museum"
                    scope: "Scope"                          # example: "European scope"
                    sector: "Sector"                        # example: "European scope"

                    city: "City"                            # example: "Slovakia"
                    street: "Street"                        # example: "Slovakia"
                    zipcode: "ZIP code"                     # example: "Slovakia"
                    po_box: "PO box"
                    country: "Country"                      # example: "Slovakia"

                    description: "Description"              # example: "<p>Long text</p>"

                    # val: "Image service Opt-in"             # example: "false"
                    # val: "DEA Sent"                         # example: "true"
                    # val: "DEA Notes"                        # example: "Long story"
                    # val: "DEA Signed"                       # example: "true"
                    # val: "Data provider"                    # example: "true"
                    # val: "Data Partner"                     # example: "false"

                    # Aggregator
                    # Alternative 3
                    # Alternative 4
                    # Alternative 5
                    # Geographic Level
                    # Lang Alternative 3
                    # Lang Alternative 4
                    # Lang Alternative 5
                    # Organisation-eigenaar
                    # Organisationnaam
                    # Provides to
                    # SameAs 1
                    # SameAs 2
                    # SameAs 3
