extensions:
  - Bolt\Extension\Europeana\ViewBlocks\ViewBlocksExtension
  - Bolt\Extension\Europeana\ZohoImport\ZohoImportExtension
  - Bolt\Extension\Europeana\SelectAsync\SelectAsyncExtension
  - Bolt\Extension\Europeana\ApiLogin\ApiLoginExtension
  - Bolt\Extension\TwoKings\FeaturedItems\FeaturedItemsExtension
