main:
    -
        class: home
        path: pages/homepage
        label: Homepage
    -
        class: mission
        path: pages/our-mission
        label: 'Our mission'
        submenu:
            -
                label: 'Our mission'
                path: pages/our-mission
            -
                label: 'About us'
                path: pages/about-us
            -
                label: 'Governing Board'
                path: pages/governing-board
    -
        class: wwd
        path: pages/what-we-do
        label: 'What we do'
        submenu:
            -
                label: Advocacy
                path: pages/advocacy
                submenu:
                    -
                        path: pages/the-europeana-rights-statement-selection-tool
                        label: 'Copyright Reform'
                    -
                        label: 'Cultural awareness'
                        path: pages/get-involved
                    -
                        label: 'Re-usable content'
                        path: pages/use-our-data
                    -
                        label: 'Benefits of Digital Humanities Research for Society'
                        path: pages/our-network
            -
                label: Standardisation
                path: pages/standardisation
                submenu:
                    -
                        label: 'Legal interoperability of data'
                        path: pages/legal-interoperability-data
                    -
                        label: 'Impact framework'
                        path: pages/impact-framework
                    -
                        label: 'Cross-domain data exchange and interoparability (EDM)'
                        path: pages/cross-domain-data-exchange
            -
                label: Discovery
                path: pages/discovery
            -
                label: 'Academic research'
                path: pages/academic-research
            -
                label: 'Creative industries'
                path: pages/creative-industries
            -
                label: CHIs
                path: pages/chis
            -
                label: Education
                path: pages/education
            -
                label: 'EU project brokerage and support'
                path: pages/project-brokerage-and-support
            -
                label: Campaigns
                path: pages/campaigns
    -
        class: network
        path: pages/network
        label: Network
        submenu:
            -
                label: 'About the network'
                path: pages/about-the-network
                submenu:
                    -
                        label: 'Management board'
                        path: pages/management-board
                    -
                        label: 'Members council'
                        path: pages/members-council
                    -
                        label: 'Network members'
                        path: pages/network-members
            -
                label: 'Specialty communities'
                path: pages/specialty-communities
                submenu:
                    -
                        label: EuropeanaTech
                        path: pages/europeanatech
                    -
                        label: EuropeanaIPR
                        path: pages/europeanaipr
                    -
                        label: Europeana4Education
                        path: pages/europeana4education
                    -
                        label: 'Europeana Research'
                        path: pages/europeana-research
                    -
                        label: 'Member states'
                        path: pages/member-states
            -
                label: 'Task forces'
                path: pages/task-forces
            -
                label: 'Working groups'
                path: pages/working-groups
            -
                label: Events
                path: events
    -
        class: services
        path: pages/services
        label: Services
        submenu:
            -
                label: 'Incubation services'
                path: pages/incubation-services
                submenu:
                    -
                        label: 'Co-creation (Wotify)'
                        link: pages/wotify
                    -
                        label: Funding
                        path: pages/funding
                        submenu:
                            -
                                label: 'Crowd and match funding (Goteo)'
                                path: pages/goteo
                            -
                                label: Grants
                                path: pages/grants
                            -
                                label: Challenges
                                path: pages/funding-challenges
                            -
                                label: 'Investor Forum'
                                path: pages/investor-forum
            -
                label: 'Publication services'
                path: pages/publication-services
                submenu:
                    -
                        label: 'Collection publication'
                        path: pages/collection-publication
                    -
                        label: 'Thematic collection publication'
                        path: pages/thematic-collection
                    -
                        label: 'Virtual exhibit publication'
                        path: pages/virtual-exhibit
                    -
                        label: 'Image service publication'
                        path: pages/image-service
                    -
                        label: 'Off Europeana publication'
                        path: pages/off-europeana-publication
                    -
                        label: 'Content marketing'
                        path: pages/content-marketing
    -
        class: resources
        path: pages/resources
        label: Resources
        submenu:
            -
                label: Statistics
                path: pages/statistics
                submenu:
                    -
                        label: 'Europeana statistics dashboard'
                        path: pages/statistics-dashboard
                    -
                        label: Enumerate
                        path: pages/enumerate
            -
                label: Standardisation
                path: pages/resources-standardisation
                submenu:
                    -
                        label: 'EDM documentation'
                        path: pages/edm-documentation
                    -
                        label: 'Europeana licencing framework'
                        path: pages/europeana-licencing-framework
                    -
                        label: 'International rightsstatements.org'
                        path: pages/international-rightsstatements-org
                    -
                        label: 'Framework documentation'
                        path: pages/framework-documentation
                    -
                        label: 'Case studies'
                        path: pages/standardisation-case-studies
                    -
                        label: 'Impact toolkit'
                        path: pages/impact-toolkit
            -
                label: Advocacy
                path: pages/resources-advocacy
                submenu:
                    -
                        label: 'Public domain charter'
                        path: pages/public-domain-charter
                    -
                        label: 'Europeana Publishing Framework'
                        path: pages/reuropeana-publishing-framework
            -
                label: 'Developer services'
                path: pages/developer-services
                submenu:
                    -
                        label: 'API consoles'
                        path: pages/api-consoles
                    -
                        label: 'Swagger specifications'
                        path: pages/swagger-specifications
                    -
                        label: 'API Documentation'
                        path: pages/api-documentation
                    -
                        label: 'Software libraries'
                        path: pages/software-libraries
            -
                label: Datasets
                path: pages/datasets
                submenu:
                    -
                        label: 'High resolution for creatives'
                        path: pages/high-resolution-for-creatives
                    -
                        label: 'Academic research'
                        path: pages/academic-research
            -
                label: 'Case studies'
                path: pages/case-studies
            -
                label: 'Ingestion tools'
                path: pages/ingestion-tools
                submenu:
                    -
                        label: Metis
                        path: pages/metis
                    -
                        label: 'Operation direct'
                        path: pages/operation-direct
            -
                label: 'Document archive'
                path: pages/document-archive
                submenu:
                    -
                        label: Publications
                        path: /resources/document-archive/publications
                    -
                        label: 'Projects incl. documents'
                        path: /resources/document-archive/projects
                    -
                        label: 'Governance documents'
                        path: /resources/document-archive/governance
                    -
                        label: 'Network documents'
                        path: /resources/document-archive/network
                    -
                        label: 'Task force recommentations'
                        path: /resources/document-archive/task-force-recommendations
            -
                label: 'Europeana branding guidelines'
                path: pages/32
secondary:
    -
        label: News
        path: pages/news
        class: secondary
        submenu:
            -
                label: Blog
                class: secondary
                path: pages/blog
            -
                label: 'Press releases'
                class: secondary
                path: pages/press-releases
            -
                label: Publications
                class: secondary
                path: pages/publications
    -
        label: Europeana.eu
        class: secondary
        link: https://www.europeana.eu
    -
        label: Join the network
        class: secondary
        path: pages/join-network
    -
        label: Get the API
        class: secondary
        path: pages/get-api
    -
        label: Jobs
        class: secondary
        path: pages/jobs
