main:
    -
        label: 'Homepage'
        path: landingpages/1
        class: first
    -
        label: 'Our mission'
        path: landingpages/2
    -
        label: 'What we do'
        path: landingpages/3
        submenu:
            -
                path: landingpages/9
                label: Advocacy
                submenu:
                    -
                        path: page/114
                        label: Copyright Reform
                    -
                        path: landingpages/36
                        label: Cultural awareness
                    -
                        path: landingpages/37
                        label: Re-usable content
                    -
                        path: landingpages/38
                        label: Copyright Reform
            -
                path: landingpages/10
                label: Standardisation
                submenu:
                    -
                        link: /page/legal-interoperability-data
                        label: Legal interoperability of data
                    -
                        link: /page/impact-framework
                        label: Impact framework
                    -
                        path: /page/cross-domain-data-exchange
                        label: Cross-domain data exchange and interoparability (EDM)
            -
                path: landingpages/11
                label: Discovery
            -
                path: landingpages/12
                label: Academic research
            -
                path: landingpages/13
                label: Creative industries
            -
                path: landingpages/14
                label: CHIs
            -
                path: landingpages/15
                label: Education
            -
                path: landingpages/16
                label: EU project brokerage and support
            -
                path: landingpages/17
                label: Campaigns
    -
        label: Network
        path: landingpages/4
        submenu:
            -
                path: landingpages/18
                label: About the network
                submenu:
                    -
                        path: persons/management-board
                        label: Management board
                    -
                        path: persons/members-council
                        label: Members council
                    -
                        path: persons/network-members
                        label: Network members
            -
                path: landingpages/19
                label: Specialty communities
                submenu:
                    -
                        path: community/tech
                        label: EuropeanaTech
                    -
                        path: community/ipr
                        label: EuropeanaIPR
                    -
                        path: community/education
                        label: Europeana4Education
                    -
                        path: community/research
                        label: Europeana Research
                    -
                        path: community/member-states
                        label: Member states
            -
                path: landingpages/20
                label: Task forces
            -
                path: landingpages/21
                label: Working groups
            -
                path: events
                label: Events
    -
        label: Services
        path: landingpages/5
        submenu:
            -
                path: landingpages/22
                label: Incubation services
                submenu:
                    -
                        link: /services/incubation/wotify
                        label: Co-creation (Wotify)
                    -
                        link: /services/incubation/funding
                        label: Funding
                        submenu:
                            -
                                link: /services/incubation/funding/goteo
                                label: Crowd and match funding (Goteo)
                            -
                                link: /services/incubation/funding/grants
                                label: Grants
                            -
                                link: /services/incubation/funding/challenges
                                label: Challenges
                            -
                                link: /services/incubation/funding/investor-forum
                                label: Investor Forum
            -
                path: landingpages/23
                label: Publication services
                submenu:
                    -
                        link: /services/publication/collection
                        label: Collection publication
                    -
                        link: /services/publication/thematic-collection
                        label: Thematic collection publication
                    -
                        link: /services/publication/virtual-exhibit
                        label: Virtual exhibit publication
                    -
                        link: /services/publication/image-service
                        label: Image service publication
                    -
                        link: /services/publication/external
                        label: Off Europeana publication
                    -
                        link: /services/publication/content-marketing
                        label: Content marketing
    -
        label: Resources
        path: landingpages/6
        submenu:
            -
                path: landingpages/24
                label: Statistics
                submenu:
                    -
                        link: /resources/statistics/statistics-dashboard
                        label: Europeana statistics dashboard
                    -
                        link: /resources/statistics/enumerate
                        label: Enumerate
            -
                path: landingpages/25
                label: Standardisation
                submenu:
                    -
                        link: /resources/standardisation/edm-documentation
                        label: EDM documentation
                    -
                        link: /resources/standardisation/europeana-licencing-framework
                        label: Europeana licencing framework
                    -
                        link: /resources/standardisation/international-rightsstatements-org
                        label: International rightsstatements.org
                    -
                        link: /resources/standardisation/framework-documentation
                        label: Framework documentation
                    -
                        link: /resources/standardisation/case-studies
                        label: Case studies
                    -
                        link: /resources/standardisation/impact-toolkit
                        label: Impact toolkit
            -
                path: landingpages/26
                label: Advocacy
                submenu:
                    -
                        link: /resources/advocacy/public-domain-charter
                        label: Public domain charter
                    -
                        link: /resources/advocacy/europeana-publishing-framework
                        label: Europeana Publishing Framework
            -
                path: landingpages/27
                label: Developer services
                submenu:
                    -
                        link: /resources/developer-services/api-consoles
                        label: API consoles
                    -
                        link: /resources/developer-services/swagger-specifications
                        label: Swagger specifications
                    -
                        link: /resources/developer-services/api-documentation
                        label: API Documentation
                    -
                        link: /resources/developer-services/software-libraries
                        label: Software libraries
            -
                path: landingpages/28
                label: Datasets
                submenu:
                    -
                        link: /resources/datasets/high-resolution-for-creatives
                        label: High resolution for creatives
                    -
                        link: /resources/datasets/academic-research
                        label: Academic research
            -
                path: landingpages/29
                label: Case studies
            -
                path: landingpages/30
                label: Ingestion tools
                submenu:
                    -
                        link: /resources/ingestion-tools/metis
                        label: Metis
                    -
                        link: /resources/ingestion-tools/operation-direct
                        label: Operation direct
            -
                path: landingpages/31
                label: Document archive
                submenu:
                    -
                        link: /resources/document-archive/publications
                        label: Publications
                    -
                        link: /resources/document-archive/projects
                        label: Projects incl. documents
                    -
                        link: /resources/document-archive/governance
                        label: Governance documents
                    -
                        link: /resources/document-archive/network
                        label: Network documents
                    -
                        link: /resources/document-archive/task-force-recommendations
                        label: Task force recommentations
            -
                path: landingpages/32
                label: Europeana branding guidelines
    -
        label: News
        path: landingpages/7
        submenu:
            -
                path: landingpages/33
                label: Blog
            -
                path: landingpages/34
                label: Press releases
            -
                path: landingpages/35
                label: Publications
    -
        label: Jobs
        path: landingpages/8
    -
        link: /page/styleguide
        label: Styleguide
        class: last
