main:
    -
        class: home
        path: pages/1
        label: Homepage
    -
        class: mission
        path: pages/2
        label: 'Our mission'
        submenu:
            -
                label: 'Our mission'
                path: pages/2
            -
                label: 'About us'
                link: page/about-us
            -
                label: 'Governing Board'
                link: /page/governing-board
    -
        class: wwd
        path: pages/3
        label: 'What we do'
        submenu:
            -
                label: Advocacy
                path: pages/9
                submenu:
                    -
                        label: 'Copyright Reform'
                        link: /page/copyright-reform
                    -
                        label: 'Cultural awareness'
                        path: pages/36
                    -
                        label: 'Re-usable content'
                        path: pages/37
                    -
                        label: 'Benefits of Digital Humanities Research for Society'
                        path: pages/38
            -
                label: Standardisation
                path: pages/10
                submenu:
                    -
                        label: 'Legal interoperability of data'
                        link: /page/legal-interoperability-data
                    -
                        label: 'Impact framework'
                        link: /page/impact-framework
                    -
                        label: 'Cross-domain data exchange and interoparability (EDM)'
                        path: /page/cross-domain-data-exchange
            -
                label: Discovery
                path: pages/11
            -
                label: 'Academic research'
                path: pages/12
            -
                label: 'Creative industries'
                path: pages/13
            -
                label: CHIs
                path: pages/14
            -
                label: Education
                path: pages/15
            -
                label: 'EU project brokerage and support'
                path: pages/16
            -
                label: Campaigns
                path: pages/17
    -
        class: network
        path: pages/4
        label: Network
        submenu:
            -
                label: 'About the network'
                path: pages/18
                submenu:
                    -
                        label: 'Management board'
                        path: page/management-board
                    -
                        label: 'Members council'
                        path: persons/members-council
                    -
                        label: 'Network members'
                        path: persons/network-members
            -
                label: 'Specialty communities'
                path: pages/19
                submenu:
                    -
                        label: EuropeanaTech
                        path: community/tech
                    -
                        label: EuropeanaIPR
                        path: community/ipr
                    -
                        label: Europeana4Education
                        path: community/education
                    -
                        label: 'Europeana Research'
                        path: community/research
                    -
                        label: 'Member states'
                        path: community/member-states
            -
                label: 'Task forces'
                path: pages/20
            -
                label: 'Working groups'
                path: pages/21
            -
                label: Events
                path: events
    -
        class: services
        path: pages/5
        label: Services
        submenu:
            -
                label: 'Incubation services'
                path: pages/22
                submenu:
                    -
                        label: 'Co-creation (Wotify)'
                        link: /services/incubation/wotify
                    -
                        label: Funding
                        link: /services/incubation/funding
                        submenu:
                            -
                                label: 'Crowd and match funding (Goteo)'
                                link: /services/incubation/funding/goteo
                            -
                                label: Grants
                                link: /services/incubation/funding/grants
                            -
                                label: Challenges
                                link: /services/incubation/funding/challenges
                            -
                                label: 'Investor Forum'
                                link: /services/incubation/funding/investor-forum
            -
                label: 'Publication services'
                path: pages/23
                submenu:
                    -
                        label: 'Collection publication'
                        link: /services/publication/collection
                    -
                        label: 'Thematic collection publication'
                        link: /services/publication/thematic-collection
                    -
                        label: 'Virtual exhibit publication'
                        link: /services/publication/virtual-exhibit
                    -
                        label: 'Image service publication'
                        link: /services/publication/image-service
                    -
                        label: 'Off Europeana publication'
                        link: /services/publication/external
                    -
                        label: 'Content marketing'
                        link: /services/publication/content-marketing
    -
        class: resources
        path: pages/6
        label: Resources
        submenu:
            -
                label: Statistics
                path: pages/24
                submenu:
                    -
                        label: 'Europeana statistics dashboard'
                        link: /resources/statistics/statistics-dashboard
                    -
                        label: Enumerate
                        link: /resources/statistics/enumerate
            -
                label: Standardisation
                path: pages/25
                submenu:
                    -
                        label: 'EDM documentation'
                        link: /resources/standardisation/edm-documentation
                    -
                        label: 'Europeana licencing framework'
                        link: /resources/standardisation/europeana-licencing-framework
                    -
                        label: 'International rightsstatements.org'
                        link: /resources/standardisation/international-rightsstatements-org
                    -
                        label: 'Framework documentation'
                        link: /resources/standardisation/framework-documentation
                    -
                        label: 'Case studies'
                        link: /resources/standardisation/case-studies
                    -
                        label: 'Impact toolkit'
                        link: /resources/standardisation/impact-toolkit
            -
                label: Advocacy
                path: pages/26
                submenu:
                    -
                        label: 'Public domain charter'
                        link: /resources/advocacy/public-domain-charter
                    -
                        label: 'Europeana Publishing Framework'
                        link: /resources/advocacy/europeana-publishing-framework
            -
                label: 'Developer services'
                path: pages/27
                submenu:
                    -
                        label: 'API consoles'
                        link: /resources/developer-services/api-consoles
                    -
                        label: 'Swagger specifications'
                        link: /resources/developer-services/swagger-specifications
                    -
                        label: 'API Documentation'
                        link: /resources/developer-services/api-documentation
                    -
                        label: 'Software libraries'
                        link: /resources/developer-services/software-libraries
            -
                label: Datasets
                path: pages/28
                submenu:
                    -
                        label: 'High resolution for creatives'
                        link: /resources/datasets/high-resolution-for-creatives
                    -
                        label: 'Academic research'
                        link: /resources/datasets/academic-research
            -
                label: 'Case studies'
                path: pages/29
            -
                label: 'Ingestion tools'
                path: pages/30
                submenu:
                    -
                        label: Metis
                        link: /resources/ingestion-tools/metis
                    -
                        label: 'Operation direct'
                        link: /resources/ingestion-tools/operation-direct
            -
                label: 'Document archive'
                path: pages/31
                submenu:
                    -
                        label: Publications
                        link: /resources/document-archive/publications
                    -
                        label: 'Projects incl. documents'
                        link: /resources/document-archive/projects
                    -
                        label: 'Governance documents'
                        link: /resources/document-archive/governance
                    -
                        label: 'Network documents'
                        link: /resources/document-archive/network
                    -
                        label: 'Task force recommentations'
                        link: /resources/document-archive/task-force-recommendations
            -
                label: 'Europeana branding guidelines'
                path: pages/32
    -
        class: news
        path: pages/7
        label: News
        submenu:
            -
                label: Blog
                path: pages/33
            -
                label: 'Press releases'
                path: pages/34
            -
                label: Publications
                path: pages/35
    -
        class: jobs
        path: pages/8
        label: Jobs
secondary:
    -
        class: secondary
        path: visual-sitemap
        label: Sitemap
    -
        class: secondary
        path: homepage
        label: Listings
    -
        class: secondary
        label: Styleguide
        link: /page/styleguide
