main:
    -
        class: first
        path: homepage
        title: 'This is the first menu item.'
        label: Home
    -
        link: /landingpages/example-landing-page
        label: 'Example Landing'
    -
        link: /page/styleguide
        label: Styleguide
