main:
    -
        label: Homepage
        path: pages/homepage
        class: home
    -
        label: 'Our mission'
        path: pages/our-mission
        class: mission
        submenu:
            -
                path: pages/about-us
                label: 'About us'
            -
                path: page/454
                label: History
            -
                path: page/453
                label: 'Who we are'
            -
                path: pages/foundation-governing-board
                label: 'Governing Board'
            -
                label: 'Office employees'
                path: page/455
    -
        label: 'What we do '
        path: pages/what-we-do
        class: wwd
        submenu:
            -
                path: pages/academic-research
                label: 'Academic research'
            -
                path: pages/advocacy
                label: Advocacy
            -
                path: pages/campaigns
                label: Campaigns
            -
                path: pages/creative-industries
                label: 'Creative industries'
            -
                path: pages/cultural-heritage-institutions
                label: 'Cultural Heritage Institutions'
            -
                path: pages/education
                label: Education
            -
                path: pages/standardisation
                label: Standardisation
            -
                path: pages/projects
                label: Projects
    -
        label: 'Network Association'
        path: page/network-association
        class: network
        submenu:
            -
                path: page/about-our-network
                label: 'About the Association'
            -
                path: page/sign-up
                label: 'Join our Association'
            -
                path: pages/management-board
                label: 'Management Board'
            -
                path: pages/members-council
                label: 'Members Council'
            -
                path: pages/network-members
                label: 'Association Members'
            -
                path: pages/special-interest-groups
                label: 'Special interest groups'
                submenu:
                    -
                        path: pages/europeanatech
                        label: EuropeanaTech
                    -
                        path: pages/europeana-education
                        label: 'Europeana Education'
                    -
                        path: pages/europeana-research
                        label: 'Europeana Research'
                    -
                        path: pages/member-states
                        label: 'Member States'
            -
                path: pages/task-forces
                label: 'Task forces'
            -
                path: pages/working-groups
                label: 'Working groups'
            -
                path: page/events
                label: Events
    -
        label: Services
        path: pages/services
        class: services
        submenu:
            -
                path: pages/incubation-services
                label: 'Incubation services'
                submenu:
                    -
                        path: page/crowd-and-matchfunding
                        label: 'Crowd and match funding (Goteo)'
                    -
                        label: 'Co-creation (Wotify)'
                        path: page/121
                    -
                        path: page/grants-programme
                        label: Grants
                    -
                        path: page/take-the-challenge
                        label: Challenges
            -
                path: pages/publication-services
                label: 'Publication services'
                submenu:
                    -
                        path: pages/collection-publication
                        label: 'Collection publication'
                    -
                        path: pages/thematic-collection
                        label: 'Thematic collection publication'
                    -
                        path: pages/virtual-exhibit
                        label: 'Virtual exhibit publication'
                    -
                        path: pages/image-service
                        label: 'Image service publication'
                    -
                        path: pages/off-europeana-publication
                        label: 'Off Europeana publication'
                    -
                        path: pages/content-marketing
                        label: 'Content marketing'
    -
        label: Resources
        path: pages/resources
        class: resources
        submenu:
            -
                path: page/europeana-brand
                label: 'Europeana brand'
                submenu:
                    -
                        label: Values
                        path: page/458
                    -
                        label: Guidelines
                        path: page/459
                    -
                        label: Templates
                        path: page/460
                    -
                        label: Skins
                        path: page/457
            -
                path: pages/apps
                label: 'Case studies'
            -
                path: pages/datasets
                label: 'Curated datasets'
            -
                path: pages/developer-services
                label: 'Developer services'
                submenu:
                    -
                        path: page/495
                        label: 'REST API'
            -
                path: pages/document-archive
                label: 'Document archive'
                submenu:
                    -
                        path: pages/publications
                        label: Publications
                    -
                        label: 'Press releases'
                        path: page/46
                    -
                        path: pages/project-list
                        label: 'Project documents'
                    -
                        path: page/governing-board-papers-documents
                        label: 'Governance documents'
                    -
                        path: page/newsletters-and-updates
                        label: 'Network documents'
                    -
                        path: pages/task-force-recommendations
                        label: 'Task force recommentations'
                    -
                        path: page/479
                        label: 'R&D recommendations'
                    -
                        path: page/164
                        label: 'Europeana in the news'
            -
                path: pages/ingestion-tools
                label: 'Ingestion tools'
            -
                path: page/480
                label: 'R&D tools'
                submenu:
                    -
                        path: page/205
                        label: FLOSS
                    -
                        path: page/316
                        label: 'Mapping EDM'
                    -
                        label: 'Semantic mindmap'
                        path: page/222
            -
                path: pages/resources-standardisation
                label: Standardisation
                submenu:
                    -
                        path: pages/edm-documentation
                        label: 'EDM documentation'
                    -
                        path: page/the-licensing-framework
                        label: 'Europeana Licencing Framework'
                    -
                        path: page/466
                        label: IIIF
                    -
                        path: page/rightsstatements-org
                        label: Rightsstatements.org
                    -
                        label: 'Public Domain calculator'
                        path: page/257
                    -
                        path: page/220
                        label: 'Glossary of Terms'
            -
                path: pages/statistics
                label: Statistics
                submenu:
                    -
                        path: pages/usage-statistics
                        label: 'Usage statistics'
                    -
                        path: pages/enumerate
                        label: Enumerate
secondary:
    -
        path: pages/join-network
        class: secondary
        label: 'Join us'
    -
        class: secondary
        path: pages/blog
        label: Blog
    -
        link: 'https://www.europeana.eu'
        class: secondary
        label: Europeana.eu
    -
        path: pages/get-api
        class: secondary
        label: 'Get the API'
    -
        path: pages/jobs
        class: secondary
        label: Jobs
    -
        label: Press
        path: page/press
