main:
    -
        label: 'Our mission '
        path: page/our-mission
        class: mission
        submenu:
            -
                path: pages/about-us
                label: 'About us'
            -
                path: page/454
                label: History
            -
                path: page/453
                label: 'Who we are'
            -
                path: pages/foundation-governing-board
                label: 'Governing Board'
            -
                label: Staff
                path: page/455
    -
        label: 'Priorities '
        path: pages/what-we-do
        class: wwd
        submenu:
            -
                path: pages/academic-research
                label: 'Academic Research'
            -
                path: pages/creative-industries
                label: 'Creative industries'
            -
                path: pages/cultural-heritage-institutions
                label: 'Cultural Heritage Institutions'
            -
                path: pages/education
                label: Education
            -
                path: pages/advocacy
                label: Advocacy
            -
                path: pages/member-states
                label: 'Member States'
            -
                label: 'Impact framework '
                path: page/533
            -
                path: pages/campaigns
                label: Campaigns
            -
                path: pages/standardisation
                label: Standardization
            -
                path: pages/projects
                label: Projects
    -
        label: 'Network Association'
        path: page/network-association
        class: network
        submenu:
            -
                path: page/about-our-network
                label: 'About the Association'
            -
                path: page/sign-up
                label: 'Join our Association'
            -
                path: pages/management-board
                label: 'Management Board'
            -
                path: pages/members-council
                label: 'Members Council'
            -
                path: pages/network-members
                label: 'Association Members'
            -
                path: pages/special-interest-groups
                label: 'Special interest groups'
                submenu:
                    -
                        path: pages/europeanatech
                        label: EuropeanaTech
                    -
                        path: pages/europeana-education
                        label: 'Europeana Education'
                    -
                        label: 'Europeana Research '
                        path: page/540
                    -
                        label: 'Europeana Art Advisory Board'
                        path: page/347
            -
                path: pages/task-forces
                label: 'Task Forces'
            -
                path: pages/working-groups
                label: 'Working Groups'
            -
                path: page/events
                label: Events
    -
        label: Services
        path: pages/services
        class: services
        submenu:
            -
                label: 'Data publication'
                path: page/23
                submenu:
                    -
                        label: 'Europeana Aggregators'
                        path: page/547
            -
                path: pages/discovery
                label: Discovery
                submenu:
                    -
                        path: pages/collections
                        label: Collections
                    -
                        path: pages/thematic-collections
                        label: 'Thematic Collections'
                    -
                        path: pages/online-exhibitions
                        label: 'Online Exhibitions'
            -
                path: pages/incubation-services
                label: 'Incubation services'
                submenu:
                    -
                        path: page/crowd-and-matchfunding
                        label: 'Crowd and match funding (Goteo)'
                    -
                        label: 'Co-creation (Wotify)'
                        path: page/121
                    -
                        path: page/grants-programme
                        label: Grants
                    -
                        path: page/take-the-challenge
                        label: Challenges
    -
        label: Resources
        path: pages/resources
        class: secondary
        submenu:
            -
                path: page/europeana-brand
                label: 'Europeana brand'
                submenu:
                    -
                        label: Values
                        path: page/458
                    -
                        label: Guidelines
                        path: page/459
                    -
                        label: Templates
                        path: page/460
                    -
                        label: Skins
                        path: page/457
            -
                path: pages/apps
                label: Apps
            -
                label: Tools
                path: page/509
            -
                path: pages/datasets
                label: 'Curated datasets'
            -
                path: pages/apis
                label: APIs
                submenu:
                    -
                        path: page/495
                        label: 'REST API'
                    -
                        label: 'Annotations API '
                        path: page/496
                    -
                        label: OAI-PMH
                        link: page/oai-pmh-service
                    -
                        path: page/499
                        label: 'Linked Open Data '
                    -
                        path: page/504
                        label: 'Image similarity API'
            -
                path: pages/document-archive
                label: 'Document archive'
                submenu:
                    -
                        path: pages/publications
                        label: Publications
                    -
                        label: 'Press releases'
                        path: page/46
                    -
                        path: pages/project-list
                        label: 'Project documents'
                    -
                        path: page/governing-board-papers-documents
                        label: 'Governance documents'
                    -
                        path: page/newsletters-and-updates
                        label: 'Network documents'
                    -
                        path: pages/task-force-recommendations
                        label: 'Task force recommentations'
                    -
                        path: page/479
                        label: 'R&D recommendations'
                    -
                        path: page/164
                        label: 'Europeana in the news'
            -
                path: pages/resources-standardisation
                label: Standardization
                submenu:
                    -
                        path: pages/edm-documentation
                        label: 'EDM documentation'
                    -
                        path: page/the-licensing-framework
                        label: 'Europeana Licencing Framework'
                    -
                        path: page/rightsstatements-org
                        label: Rightsstatements.org
                    -
                        label: 'Public Domain calculator'
                        path: page/257
                    -
                        path: page/220
                        label: 'Glossary of Terms'
            -
                path: pages/statistics
                label: Statistics
                submenu:
                    -
                        path: pages/europeana-usage-statistics
                        label: 'Usage statistics'
                    -
                        path: pages/enumerate
                        label: Enumerate
secondary:
    -
        path: pages/sign-up
        class: secondary
        label: 'Join us'
    -
        class: secondary
        path: pages/blog
        label: Blog
    -
        link: 'https://www.europeana.eu'
        class: secondary
        label: 'Europeana Collections'
    -
        path: pages/get-api
        class: secondary
        label: 'Get the API'
    -
        path: pages/jobs
        class: secondary
        label: Jobs
    -
        label: Press
        class: secondary
        path: page/press
footer:
    -
        label: Home
        path: pages/home
    -
        label: 'Terms & policies'
        link: 'http://europeana.eu/portal/rights/terms-and-policies.html'
    -
        label: 'Contact us'
        path: pages/contact-us
    -
        label: Sitemap
        path: sitemap
