# This file defines role-based access control for your Bolt site.
roles:
    editor:
        description: This user can edit some content.
        label: Editor
    chief-editor:
        description: This user can edit any content in the system.
        label: Chief Editor
    admin:
        description: User-level administrator.
        label: Administrator
    developer:
        description: Developer access. Only required to change system-level settings.
        label: Developer
#    guest:
#        description: This user can log on, but is not allowed to edit any content.
#        label: Guest Editor

# Role hierarchy settings
roles-hierarchy:
    manipulate:
        admin: [ ]
        developer: [ admin ]
        chief-editor: [ admin, developer ]
        editor: [ admin, developer ]
        guest: [ admin, developer ]

global:
    about: [ everyone ] # view the 'About Bolt' page
    clearcache: [ developer ]
    contentaction: [ admin, developer ]
    dashboard: [ everyone ]
    dbcheck: [ developer ]
    dbupdate: [ developer ]
    dbupdate_result: [ developer ]
    extensions: [ developer ]
    extensions:config: [ developer ]
    fileedit: [ admin, developer ]
    files:config: [ developer ]
    files:theme: [ developer ]
    files:uploads: [ admin, developer, chief-editor ]
    files: [ admin, developer, chief-editor, editor ]
    prefill: [ developer ]
    profile: [ everyone ] # edit own profile
    settings: [ admin, developer, everyone ]
    translation: [ developer ]
    useraction: [ admin, developer ] # enable/disable/delete
    useredit: [ admin, developer ] # user settings
    users: [ admin, developer ] # view user overview
    roles: [ admin, developer ] # view the roles overview
    maintenance-mode: [ everyone ] # view the frontend when in maintenance mode
    omnisearch: [ everyone ]
    # Access to the various logs
    changelog: [ developer ]
    systemlog: [ developer ]
    # The following permissions are particularly important: login and postLogin
    # determine who may see and use the login form. If you set them to anything
    # but 'anonymous', only users will be able to log in that are logged in
    # already, which is probably never what you want.
    login: [ anonymous ]
    postLogin: [ anonymous ]
    # Likewise, 'logout' needs to be granted to 'everyone', otherwise people
    # cannot log out anymore.
    logout: [ everyone ]

contenttype-all:
    edit: [ developer, admin ]
    create: [ developer, admin ]
    publish: [ developer, admin ]
    depublish: [ developer, admin ]
    delete: [ developer, admin ]
    change-ownership: [ developer, admin ]

contenttype-default:
    edit: [ developer, admin, owner ]
    create: [ developer, admin, owner ]
    change-ownership: [ developer, admin, owner ]
    depublish: [ developer, admin, owner ]
    delete: [ developer, admin ]
    view: [ anonymous ]

contenttypes:
    pages:
        edit: [ developer, admin ]
        create: [ developer, admin ]
        publish: [ developer, admin ]
        depublish: [ developer, admin ]
        change-ownership: [ owner ]
        view: [ chief-editor ]
    posts:
        edit: [ chief-editor ]
        create: [ chief-editor ]
        publish: [ chief-editor ]
        depublish: [ chief-editor ]
    data:
        edit: [ chief-editor ]
        create: [ chief-editor ]
        publish: [ chief-editor ]
        depublish: [ chief-editor ]
    projects:
        edit: [ chief-editor ]
        create: [ chief-editor ]
        publish: [ chief-editor ]
        depublish: [ chief-editor ]
    events:
        edit: [ chief-editor ]
        create: [ chief-editor ]
        publish: [ chief-editor ]
        depublish: [ chief-editor ]
    jobs:
        edit: [ chief-editor ]
        create: [ chief-editor ]
        publish: [ chief-editor ]
        depublish: [ chief-editor ]
    banners:
        edit: [ chief-editor ]
        create: [ chief-editor ]
        publish: [ chief-editor ]
        depublish: [ chief-editor ]
    blogposts:
        edit: [ chief-editor, editor ]
        create: [ chief-editor, editor ]
        publish: [ chief-editor, editor ]
        depublish: [ chief-editor, editor ]
    blogevents:
        edit: [ chief-editor, editor ]
        create: [ chief-editor, editor ]
        publish: [ chief-editor, editor ]
        depublish: [ chief-editor, editor ]
