.base: &base
    hostname: kwabbernoot/test
    user: deploy
    stage: test
    application: cope
    deploy_path: /raiddata/www/cope
    shared_files_path: /2kdata/dev/289_europeana/websites/europeana_files
    thumb_files_path: /raiddata/www/cope/shared/thumbs
    repository: git@github.com:europeana/EuropeanaCopeBolt.git
    mysql_host: localhost
    mysql_db: europeana_cope
    git_tty: true
    keep_releases: 10
    cleanup_use_sudo: true
    snapshots_dir: snapshots
    shared_files: 
      - '.bolt.yml'
    keep_files: 
      - 'app/config/menu.yml'
      - 'app/config/taxonomy.yml'
    writable_dirs:   
      - 'app/config'
      - 'app/config/extensions'
      - 'app/database'
      - 'extensions'
      - 'public'
      - 'public/bolt-public'
    allow_anonymous_stats: false

cope.twokings.eu:
    <<: *base
    hostname: kwabbernoot/test
    stage: test
    application: cope
    keep_releases: 3
    deploy_path: /raiddata/www/cope
    shared_files_path: /2kdata/dev/289_europeana/websites/europeana_files
    thumb_files_path: /raiddata/www/cope/shared/thumbs
    repository: git@github.com:europeana/EuropeanaCopeBolt.git
    mysql_host: 192.168.3.9
    mysql_db: lodewijk_europeana_pro

cope-test.eanadev.org:
    <<: *base
    hostname: pro-beta.europeana.eu
    user: deploy
    stage: accept
    default_branch: release
    application: cope
    keep_releases: 10
    deploy_path: /var/www/cope
    shared_files_path: "/home/dropbox/Dropbox\\ \\(Europeana\\ Pro\\)"
    thumb_files_path: /var/www/cope/shared/thumbs
    repository: git@github.com:europeana/EuropeanaCopeBolt.git
    mysql_host: localhost
    mysql_db: copedb

pro.europeana.eu:
    <<: *base
    hostname: pro.europeana.eu
    user: deploy
    stage: production
    default_branch: release
    application: cope
    keep_releases: 10
    deploy_path: /var/www/cope
    shared_files_path: "/home/dropbox/Dropbox\\ \\(Europeana\\ Pro\\)"
    thumb_files_path: /var/www/cope/shared/thumbs
    repository: git@github.com:europeana/EuropeanaCopeBolt.git
    mysql_host: localhost
    mysql_db: copedb
